services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts-jdk21
    ports:
      - "8080:8080"
    volumes:
      - "${PWD}/jenkins_home:/var/jenkins_home"
    networks:
      - net
  remote_host:
    container_name: remote-host
    image: remote-host
    build:
      context: docker-container-ubuntu
    networks:
      - net
      
networks:
  net: